apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r2dy4hnzv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r2dy4hnzv-python 
  name: r2dy4hnzv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r2dy4hnzv-python 
